version: '3.7'

services:

  ubuntu20_04-swift5_3:
      build:
        context: .
        dockerfile: Dockerfile.ubuntu20_04_swift5_3
      container_name: carton_ubuntu20_04-swift5_3
      command:
        - /bin/bash
        - -c
        - |
          ls -alF
          mkdir wasp
          cd wasp
          carton init --template tokamak
          carton dev
      ports:
        - "9080:8080"

  ubuntu18_04-swift5_3:
      build:
        context: .
        dockerfile: Dockerfile.ubuntu18_04_swift5_3
      container_name: carton_ubuntu18_04-swift5_3
      # command:
      #   - /bin/bash
      #   - -c
      #   - |
      #     ls -alF
      #     mkdir wasp
      #     cd wasp
      #     carton init --template tokamak
      #     carton dev
      ports:
        - "9080:8080"

  from_swift:
    build:
      context: .
      dockerfile: Dockerfile.fromswift53
    container_name: swift_base
    command:
      - /bin/bash
      - -c
      - |
        ls -alF
        mkdir wasp
        cd wasp
        carton init --template tokamak
        carton dev
    ports:
      - "9080:8080"
